### ISSUE TITLE
What is FOCAL?

### ISSUE THREAD

**Issue by m-stgt** [gomi42/FocalMaster#1]
In READEM.md you state _FOCAL means "Forty One Calculator Language"_. This should be prefixed by **in this context**, otherwise the proposition in Wikipedia is wrong _[FOCAL (acronym for Formulating On-line Calculations in Algebraic Language, or FOrmula CALculator[...]](https://en.wikipedia.org/wiki/FOCAL_(programming_language))_ and you should correct Wikipedia.
Frankly, IMO the idea to baptise the way to program the HP41 also "FOCAL" is not too clever. In addition, it's a ridiculous attempt to try by that to upvalue the HP41 version of keystroke programming and ennoble it to the rank like FORTRAN, BASIC, REXX, and alike.

**Comment by gomi42** [comment]
Thx for your personal opinion.

**Comment by m-stgt** [comment]
My opinion is one part, the other is [what Wikipedia lists for FOCAL](https://en.wikipedia.org/wiki/List_of_programming_languages#F). But let's face it, facts are for beginners, I know.
