### ISSUE TITLE
No barcodes found

### ISSUE THREAD

**Issue by m-stgt** [gomi42/FocalMaster#2]
![sdw 1st draft](https://github.com/gomi42/FocalMaster/assets/116765412/131027f7-7d83-46e7-8a02-519b77734739)
This is a screen shot of a description (draft) of my [Software Defined Wand (SDW)](http://hp41.org/html/ooNUlb.htm#SDW), that works quite well with [NutEm/PC](http://www.hp41.org/LibView.cfm?Command=View&ItemID=2136) when running an HP41.
Problem with "FocalMaster": see subject.
Note: the routine comprised in the shown barcode is licensed under the [QPL](http://www.hercules-390.eu/herclic.html).

**Comment by gomi42** [comment]
Indeed you found the currently existing limitation of the scanner. It does not find barcodes that are surrounded by text. The barcodes need to placed on a blank page right now :-(

**Comment by m-stgt** [comment]
Confirmed. Clipping the BC works, even in this reduced size showing moiré effect.

**Comment by gomi42** [comment]
Released version v1.2 implements of a new barcode finding algorithm, barcodes are now found within text, your given screen shot was a good test.
