### ISSUE TITLE
wrong interpreted END in RAW file

### ISSUE THREAD

**Issue by m-stgt** [gomi42/FocalMaster#4]
Importing attached RAW file shows a LBL in line 120 while in fact it is an END.
[snsnn.zip](https://github.com/gomi42/FocalMaster/files/11893259/snsnn.zip)
**Note**: the routine in the RAS file is licensed under the [QPL](http://www.hercules-390.eu/herclic.html).

BTW, RAW files as written by V41 and those written by Emu42 when running a HP42S may _by chance_ jeopardize a virtual calculator when used in the wrong emulator. This is why I suggest to tag RAW files. Within [NutEm/PC](http://www.hp41.org/LibView.cfm?Command=View&ItemID=2136) I do so by setting both, the "decompile" and "rePACK" indicator in the END.

**Comment by gomi42** [comment]
Hm, that's a bit strange. The HP manual "Creating your own hp-41 bar code" states on page 50 that the "End" instruction is coded as "CA 00 2F". But your RAW file contains the sequence "CA 0B 09". The second byte can be ignored, its variable. The third byte is the key. 
The End instruction is a special case of a label. On the other hand page 47 states that the high nibble of byte 3 must be "F" to be a valid alpha label. I'll change the detection of the End that way that anything else than F will lead to End.

Do you have some more information where to set the "decompile" and "rePACK" indicators?

**Comment by m-stgt** [comment]
IMO a must-have:
![Synth_1](https://github.com/gomi42/FocalMaster/assets/116765412/2973a014-16df-461e-ad1c-3dbd5cf6b39b)
![Synth_2](https://github.com/gomi42/FocalMaster/assets/116765412/cf2ec972-d10d-47a4-bf62-dc176d997837)
See back side for explanation of 3-byte instructions.

**Comment by gomi42** [comment]
Thx a lot. I have the book "Synthetic Programming" but without this wonderful card. Once read on your card I found the info in the book.

**Comment by m-stgt** [comment]
> Hm, that's a bit strange. The HP manual "Creating your own hp-41 bar code" states on page 50 that the "End" instruction is coded as "CA 00 2F". But your RAW file contains the sequence "CA 0B 09". [...]

BTW, RAW files are an enhancement of emulators/simulations and therefore without reference to barcodes and/or manuals from HP.

**Comment by gomi42** [comment]
I just released v1.1 that addresses this issue.

**Comment by m-stgt** [comment]
I may confirm, no problem any more with line 120 of this single RAW file in OP, but I did not test others.
In addition, RAW files if written by "FocalMaster" 1.1 are tagged _For Use With HP41_.
