### ISSUE TITLE
PDF questionable quality

### ISSUE THREAD

**Issue by m-stgt** [gomi42/FocalMaster#5]
While the export of BC as JPG looks suitable on screen, the PDF must be zoomed at least by 125% (my screen resolution is 1440x900). At zoom 100% it "drowns".
[%T.pdf](https://github.com/gomi42/FocalMaster/files/11893743/T.pdf)

**Comment by gomi42** [comment]
You notice the scalability of the PDF and the barcodes and the rounding on the screen. The size of the bars is set according the manual in pt (1/72 inch). The width of the small bars is about 0.5 mm. 

I cannot increase the size of the bars because 16 byte won't fit on a page in a single row.
